name: Deploy to Azure
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with: { ruby-version: "3.2" }
      - run: bundle install
      - uses: azure/webapps-deploy@v2
        with:
          app-name: "yourapp"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
